import random
from datetime import datetime, timedelta
from sqlalchemy import create_engine, Column, Integer, String, Text, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import time


# === Koneksi ke Database ===
db_config = {
    "host": "localhost",
    "port": 3306,
    "user": "root",
    "password": "",
    "database": "analisis_sentimen_kejagung_db"
}
db_url = f"mysql+pymysql://{db_config['user']}:{db_config['password']}@{db_config['host']}:{db_config['port']}/{db_config['database']}"
engine = create_engine(db_url)
Session = sessionmaker(bind=engine)
session = Session()
Base = declarative_base()

# === Definisi Model Tabel ===


class KomentarMentah(Base):
    __tablename__ = 'komentar_mentah'

    id = Column(Integer, primary_key=True)
    video_id = Column(String(100), nullable=False)
    kata_kunci = Column(String(100), nullable=False)
    username = Column(String(100), nullable=False)
    comment = Column(Text, nullable=False)
    likes = Column(Integer, default=0)
    replies = Column(Integer, default=0)
    tanggal_komentar = Column(DateTime, nullable=False)


# === Fungsi untuk Generate Username ===


def generate_username():
    usernames = [
        "aditya.hakim", "bella.santoso", "cindy.kurniawan", "david.rahma", "elisa.permana",
        "faisal.nurul", "gita.safira", "hendra.amalia", "intan.kusuma", "joni.rosita",
        "karina.nuraini", "lisa.rahayu", "mario.mulyani", "nina.kurnia", "oki.firman",
        "putri.rahmawati", "qori.sari", "raka.permana", "salsa.nuraini", "taufik.kusuma",
        "ulfa.rosita", "vera.amalia", "wahyu.nurul", "xena.kurniawan", "yoga.rahayu",
        "zaki.safira", "andika.rahma", "bunga.kusuma", "cahyo.permana", "dwi.nuraini",
        "eko.rosita", "fitri.amalia", "galuh.kurniawan", "hani.rahmawati", "imam.sari",
        "jihan.kusuma", "kiki.nurul", "lia.permana", "mira.rahayu", "naufal.safira",
        "oki.amalia", "putra.kurnia", "qiana.rosita", "reza.nuraini", "santi.kusuma",
        "tari.rahma", "udin.permana", "vina.nurul", "wulan.amalia", "yuni.kurniawan",
        "zara.rahayu", "agus.safira", "bella.kusuma", "citra.nuraini", "daniel.rosita",
        "elmo.amalia", "farah.kurnia", "gilang.rahmawati", "haris.permana", "ika.nurul",
        "joni.kusuma", "karin.rahayu", "lucky.safira", "mega.amalia", "niko.kurniawan",
        "olga.rosita", "prima.nuraini", "qila.permana", "rendy.rahma", "siska.kusuma",
        "tio.nurul", "ulya.amalia", "vera.kurnia", "wawan.rahayu", "xenia.safira",
        "yudha.kusuma", "zidan.permana", "anggi.nuraini", "bayu.rosita", "chelsea.amalia",
        "dian.kurniawan", "elvira.rahmawati", "fina.permana", "gita.nurul", "hendra.kusuma",
        "ika.rahayu", "joni.safira", "karina.amalia", "lucky.kurnia", "mega.rosita",
        "niko.nuraini", "olivia.permana", "prima.rahma", "qila.kusuma", "rendy.nurul",
        "siska.amalia", "taufik.kurniawan", "ulfa.rahayu", "vina.safira", "wahyu.kusuma",
        "adit.safira", "bella.kurnia", "citra.amalia", "dimas.nuraini", "eka.rahmawati",
        "fajar.kusuma", "gita.permana", "hadi.nurul", "intan.rosita", "joni.kurniawan",
        "karina.rahayu", "lisa.safira", "mario.amalia", "nina.kusuma", "oki.nuraini",
        "putri.permana", "qori.rahma", "raka.kurnia", "salsa.nurul", "taufik.rosita",
        "ulfa.amalia", "vera.kusuma", "wahyu.nuraini", "xena.permana", "yoga.rahmawati",
        "zaki.kurniawan", "andika.safira", "bunga.nurul", "cahyo.amalia", "dwi.kusuma",
        "eko.rahayu", "fitri.permana", "galuh.nuraini", "hani.rosita", "imam.kurnia",
        "jihan.rahma", "kiki.nurul", "lia.kusuma", "mira.permana", "naufal.amalia",
        "oki.rahayu", "putra.kurniawan", "qiana.safira", "reza.nuraini", "santi.kusuma",
        "tari.rahmawati", "udin.permana", "vina.nurul", "wulan.kurnia", "yuni.amalia",
        "zara.rahayu", "agus.kusuma", "bella.nuraini", "citra.permana", "daniel.rahma",
        "elmo.kurniawan", "farah.safira", "gilang.nurul", "haris.amalia", "ika.kusuma",
        "joni.rahayu", "karin.permana", "lucky.nuraini", "mega.rosita", "niko.kurnia",
        "olga.rahmawati", "prima.kusuma", "qila.nurul", "rendy.amalia", "siska.kurniawan",
        "tio.rahayu", "ulya.safira", "vera.nuraini", "wawan.permana", "xenia.rahma",
        "yudha.kusuma", "zidan.nurul", "anggi.amalia", "bayu.kurnia", "chelsea.rosita",
        "dian.permana", "elvira.nuraini", "fina.kusuma", "gita.rahayu", "hendra.safira",
        "ika.amalia", "joni.kurnia", "karina.nurul", "lucky.permana", "mega.rahmawati",
        "niko.kusuma", "olivia.nuraini", "prima.rosita", "qila.kurniawan", "rendy.rahayu",
        "siska.safira", "taufik.amalia", "ulfa.kusuma", "vina.permana", "wahyu.nurul",
        "adrian.kusuma", "bella.rahmawati", "cindy.permana", "david.safira", "elvira.nuraini",
        "adit.maulana", "bella.nurul", "citra.sari", "dimas.ramadhan", "eka.putri",
        "fajar.hakim", "gita.rahma", "hadi.permana", "intan.kusuma", "joni.amalia",
        "karina.maya", "lisa.rosita", "mario.nuraini", "nina.safira", "oki.mulyani",
        "putri.rahayu", "qori.kurniawan", "raka.firman", "salsa.amanda", "taufik.kusuma",
        "ulfa.hidayat", "vera.nurul", "wahyu.santoso", "xena.rahmawati", "yoga.permana",
        "zaki.maulida", "andika.rosita", "bunga.kurnia", "cahyo.amalia", "dwi.rizky",
        "eko.safira", "fitri.nuraini", "galuh.rahayu", "hani.kusuma", "imam.mulyani",
        "jihan.permana", "kiki.rahmawati", "lia.amanda", "mira.kurniawan", "naufal.sari",
        "oki.hidayat", "putra.nurul", "qiana.rosita", "reza.maulida", "santi.kusuma",
        "tari.rahma", "udin.permana", "vina.nuraini", "wulan.safira", "yuni.amalia",
        "zara.kurniawan", "agus.rahayu", "bella.kusuma", "citra.nurul", "daniel.mulyani",
        "elmo.permana", "farah.rahmawati", "gilang.amanda", "haris.kurnia", "ika.sari",
        "joni.hidayat", "karin.nuraini", "lucky.rosita", "mega.kusuma", "niko.permana",
        "olga.rahma", "prima.nurul", "qila.amalia", "rendy.kurniawan", "siska.safira",
        "tio.rahayu", "ulya.kusuma", "vera.mulyani", "wawan.permana", "xenia.nuraini",
        "yudha.rahmawati", "zidan.amanda", "anggi.kurnia", "bayu.sari", "chelsea.hidayat",
        "dian.kusuma", "elvira.nurul", "fina.permana", "gita.rahmawati", "hendra.amalia",
        "ika.kurniawan", "joni.safira", "karina.nuraini", "lucky.rahayu", "mega.kusuma",
        "niko.mulyani", "olivia.permana", "prima.rahma", "qila.nurul", "rendy.kurnia",
        "siska.amalia", "taufik.rosita", "ulfa.kusuma", "vina.permana", "wahyu.nuraini",
        "aditya.kurniawan", "bella.rahmawati", "cindy.permana", "david.santoso", "elisa.nuraini",
        "faisal.hidayat", "gita.maulida", "hendra.rosita", "intan.amalia", "joni.rizky",
        "karina.safira", "lisa.mulyani", "mario.kusuma", "nina.rahayu", "oki.firman",
        "putri.anggun", "qori.kurnia", "raka.hakim", "salsa.nurul", "taufik.permana",
        "ulfa.sari", "vera.amanda", "wahyu.ramadhan", "xena.maulida", "yoga.hidayat",
        "zaki.rosita", "andika.nuraini", "bunga.maya", "cahyo.kusuma", "dwi.safira",
        "eko.amalia", "fitri.rahma", "galuh.mulyani", "hani.kurniawan", "imam.permana",
        "jihan.rosita", "kiki.rizky", "lia.nurul", "mira.hidayat", "naufal.santoso",
        "oki.maulida", "putra.rahayu", "qiana.amanda", "reza.kusuma", "santi.firman",
        "tari.nuraini", "udin.anggun", "vina.rahmawati", "wulan.kurnia", "yuni.permana",
        "zara.safira", "agus.amalia", "bella.mulyani", "citra.rosita", "daniel.hidayat",
        "elmo.kusuma", "farah.nuraini", "gilang.permana", "haris.rahayu", "ika.firman",
        "joni.amanda", "karin.maulida", "lucky.rizky", "mega.santoso", "niko.rahma",
        "olga.kurniawan", "prima.safira", "qila.amalia", "rendy.nurul", "siska.hidayat",
        "tio.kusuma", "ulya.rahmawati", "vera.permana", "wawan.santoso", "xenia.nuraini",
        "yudha.amanda", "zidan.kusuma", "anggi.rosita", "bayu.rizky", "chelsea.maulida",
        "dian.hidayat", "elvira.permana", "fina.safira", "gita.amalia", "hendra.kurnia",
        "ika.rahayu", "joni.mulyani", "karina.rosita", "lucky.firman", "mega.nuraini",
        "niko.amanda", "olivia.kusuma", "prima.rahmawati", "qila.permana", "rendy.santoso",
        "siska.amalia", "taufik.nurul", "ulfa.kurniawan", "vina.rosita", "wahyu.maulida",
        "adrian.hidayat", "bella.maulida", "cindy.anggun", "david.rizky", "elvira.kusuma",
        "fajar.permana", "gita.safira", "hendra.amalia", "intan.rahmawati", "joni.nuraini",
        "karina.mulyani", "lisa.rosita", "mario.kurniawan", "nina.firman", "oki.santoso",
        "putri.rahayu", "qori.amanda", "raka.hidayat", "salsa.kusuma", "taufik.rizky",
        "ulfa.maulida", "vera.anggun", "wahyu.safira", "xena.permana", "yoga.amalia",
        "zaki.rahma", "andika.nuraini", "bunga.mulyani", "cahyo.rosita", "dwi.kurniawan",
        "eko.firman", "fitri.rahayu", "galuh.amanda", "hani.rizky", "imam.santoso",
        "jihan.kusuma", "kiki.maulida", "lia.hidayat", "mira.permana", "naufal.safira",
        "oki.amalia", "putra.rahmawati", "qiana.nuraini", "reza.kusuma", "santi.anggun",
        "tari.firman", "udin.rosita", "vina.kurniawan", "wulan.amanda", "yuni.rizky",
        "zara.hidayat", "agus.maulida", "bella.rahayu", "citra.safira", "daniel.permana",
        "elmo.amalia", "farah.kusuma", "gilang.nuraini", "haris.mulyani", "ika.rosita",
        "joni.kurniawan", "karin.firman", "lucky.rahmawati", "mega.santoso", "niko.amanda",
        "olga.rizky", "prima.hidayat", "qila.kusuma", "rendy.maulida", "siska.anggun",
        "tio.permana", "ulya.safira", "vera.amalia", "wawan.rahayu", "xenia.firman",
        "yudha.rosita", "zidan.kurniawan", "anggi.nuraini", "bayu.mulyani", "chelsea.kusuma",
        "dian.rahmawati", "elvira.permana", "fina.safira", "gita.amanda", "hendra.rizky",
        "ika.hidayat", "joni.anggun", "karina.maulida", "lucky.firman", "mega.rosita",
        "niko.kurniawan", "olivia.rahayu", "prima.amalia", "qila.nuraini", "rendy.kusuma",
        "siska.permana", "taufik.safira", "ulfa.amanda", "vina.rahmawati", "wahyu.mulyani"
        "xena.kurniawan", "yoga.firman", "zaki.rosita", "andika.rizky", "bunga.hidayat",
    ]
    return random.choice(usernames)


komentar_list = [
    "Alhamdulillah, satu lagi kasus korupsi berhasil diungkap Kejaksaan Agung!",
    "Kejaksaan Agung makin beringas! Korupsi gak dikasih ruang sama sekali!",
    "Subhanallah, penanganan kasus korupsi makin cepat dan tegas!",
    "Salut buat Kejagung, gebrakannya melawan korupsi benar-benar terasa sampai ke akar!",
    "Masya Allah, luar biasa kerja keras tim Jaksa dalam membabat korupsi!",
    "Sudah saatnya Kejaksaan Agung jadi simbol ketegasan lawan korupsi!",
    "Bravo Kejaksaan! Ini baru revolusi penegakan hukum anti korupsi!",
    "Setiap korupsi dibongkar, rasa percaya pada keadilan sedikit demi sedikit pulih!",
    "Kejaksaan Agung layak jadi contoh institusi yang berani lawan kejahatan korupsi!",
    "Alhamdulillah ya Allah, keadilan mulai berdiri tegak untuk rakyat kecil!",
    "Sumpah bangga! Kejagung gak banyak bacot, langsung sikat korupsi besar!",
    "Ga cuma omdo, Kejaksaan beneran aksi! Korupsi jadi musuh nyata!",
    "Kejaksaan sekarang kayak superhero buat rakyat lawan korupsi!",
    "Buat Kejagung: gas terus! Biar negeri ini bebas dari racun korupsi!",
    "Aksi Kejaksaan ngebasmi korupsi itu kayak oase di tengah gurun ketidakadilan!",
    "Penjara makin penuh? Bagus! Itu artinya koruptor udah gak aman lagi!",
    "Ya Allah, terima kasih masih ada penegak hukum seperti Jaksa Agung sekarang!",
    "Makin banyak kasus korupsi terbongkar, makin yakin hukum masih hidup!",
    "Kejaksaan bener-bener bawa harapan di tengah bobroknya birokrasi!",
    "Subhanallah, dari yang dulu skeptis, sekarang jadi optimis sama Kejagung!",
    "Korupsi makin gak punya tempat di negeri ini, Kejaksaan on fire!",
    "Kalau tiap minggu ada tangkapan korupsi, berarti Jaksa kerja bener!",
    "Kejagung adalah tamparan keras buat semua yang masih coba korupsi!",
    "Langkah Kejaksaan sekarang brutal tapi dibutuhkan. Jangan kasih ampun!",
    "Bukan cuma tegas, tapi juga strategis. Salut buat Kejaksaan!",
    "Kita butuh lebih banyak lembaga seperti Kejagung dalam perang lawan korupsi!",
    "Ini yang disebut keberanian: lawan korupsi di depan mata!",
    "Gue merinding tiap lihat Kejagung umumin penangkapan pelaku korupsi besar!",
    "Setiap jaksa yang jujur, itu berkah buat negeri ini. Korupsi harus lenyap!",
    "Alhamdulillah akhirnya hukum jalan, bukan cuma dekorasi!",
    "Aku percaya Kejaksaan bisa bersihkan negeri ini dari darah-darah korupsi!",
    "Subhanallah, terobosan penegakan hukum seperti ini yang kita nanti!",
    "Berantas korupsi kayak Kejagung? Baru bisa dibilang kerja nyata!",
    "Kejagung hari ini = harapan baru buat Indonesia yang bersih!",
    "Masya Allah, makin hari makin keliatan taring Kejaksaan!",
    "Salut tanpa batas buat jaksa-jaksa yang tidak tunduk pada uang!",
    "Kebangkitan hukum dimulai dari keberanian Kejaksaan hadapi korupsi!",
    "Setiap penangkapan koruptor = satu langkah lebih dekat ke keadilan!",
    "Kejagung jangan kendur! Korupsi masih banyak yang nunggu giliran!",
    "Aku bangga jadi rakyat Indonesia ketika Kejaksaan berani begitu!",
    "Ya Allah lindungi para jaksa bersih dan berani, mereka benteng terakhir kami!",
    "Kejagung is on fire! Seret semua pelaku korupsi sampai ke ujung dunia!",
    "Gak perlu gimmick, cukup kerja keras kayak Kejaksaan sekarang!",
    "Ini baru brutal positif! Korupsi gak ada tempat sembunyi lagi!",
    "Kejaksaan Agung bikin rakyat kembali punya harapan!",
    "Kalau semua aparat kayak Kejagung, korupsi pasti tinggal sejarah!",
    "Aku rasa Kejaksaan sekarang udah masuk fase DEWA untuk lawan korupsi!",
    "Berantas korupsi itu jihad! Terima kasih Kejaksaan yang konsisten!",
    "Ga cuma serem di media, Kejaksaan bener-bener sikat habis korupsi!",
    "Saya doakan jaksa-jaksa baik dapat balasan terbaik dari Allah!",
    "Di tengah gelapnya birokrasi, Kejaksaan seperti cahaya terang harapan!",
    "Kejagung bikin koruptor ngeri, rakyat pun berseri!",
    "Penegakan hukum yang bener tuh begini, bukan obral pencitraan!",
    "Kerja Kejaksaan seperti ini harus terus dijaga dan didukung penuh!",
    "Korupsi gak ada obatnya kecuali Kejagung yang turun tangan!",
    "Bersih-bersih negara dari korupsi itu jihad, dan Kejagung adalah mujahidnya!",
    "Alhamdulillah, makin sedikit koruptor yang bisa tidur nyenyak!",
    "Tiap koruptor ketangkep itu hadiah buat rakyat!",
    "Brutal dan bermanfaat! Saya cinta Kejaksaan Agung!",
    "Semoga Kejagung terus diberi kekuatan, negeri ini butuh pahlawan nyata!",
    "Setiap langkah Kejagung membasmi korupsi, adalah harapan untuk generasi depan!",
    "Kejaksaan gak main-main, ini perang besar untuk masa depan bangsa!",
    "Saya berdiri bersama Kejaksaan. Lawan korupsi sampai ke akar!",
    "Penjara bukan akhir, tapi permulaan untuk negeri bebas korupsi!",
    "Koruptor harus takut! Jaksa sekarang bukan jaksa yang dulu!",
    "Indonesia bebas korupsi itu bukan mimpi, selama Kejagung masih konsisten!",
    "Kejaksaan sekarang bukan cuma menegakkan hukum, tapi menginspirasi bangsa!",
    "Korupsi ditangani kayak begini? Saya siap jadi relawan Kejaksaan!",
    "Gak sabar lihat berita tangkapan koruptor selanjutnya!",
    "Ini brutal positif, bukan main! Tangkap semua tanpa pandang bulu!",
    "Keberanian Kejaksaan = doa jutaan rakyat kecil yang dizalimi korupsi!",
    "Ini baru brutal! Koruptor dibabat, rakyat bersorak!",
    "Ya Allah, pelihara niat mulia para jaksa yang berjuang tanpa pamrih!",
    "Gak ada kata lain selain TERIMA KASIH KEJAKSAAN!",
    "Bikin korupsi kayak dosa terbesar yang gak bisa diampuni!",
    "Setiap penangkapan itu kemenangan kecil untuk bangsa besar!",
    "Gue nangis liat jaksa berani ngomong jujur di depan publik soal korupsi!",
    "Yang penting sekarang: JANGAN KENDOR!",
    "Subhanallah, Kejagung sekarang bener-bener jadi simbol harapan!",
    "Saya percaya, meskipun lambat, korupsi akan habis kalau Kejaksaan kayak gini!",
    "Masya Allah, semoga ini jadi awal kebangkitan bangsa lawan korupsi!",
    "Buat para jaksa hebat: teruslah jadi cahaya di tengah gelapnya sistem!",
    "Berkat Kejaksaan, korupsi bukan hal yang tabu lagi untuk diungkap!",
    "Kalau korupsi adalah penyakit, Kejaksaan Agung adalah dokternya!",
    "Gue bangga banget sama Kejaksaan Agung! Brutal tapi penuh berkah!",
    "Bismillah, satu persatu koruptor tertangkap, insya Allah bersih negeri ini!",
    "Terima kasih Kejagung, kalian inspirasi anak muda seluruh negeri!",
    "Jaksa sekarang bukan cuma penegak hukum, tapi pahlawan rakyat!",
    "Kejaksaan Agung layak jadi cerita heroik di buku sejarah nanti!",
    "Alhamdulillah! Rakyat masih punya harapan di tengah badai korupsi!",
    "Ya Allah kuatkan langkah Kejaksaan, karena jalan ini penuh rintangan!",
    "Korupsi itu racun, Kejaksaan itu penawarnya!",
    "Saya gak takut lagi karena tahu Kejaksaan berdiri bersama rakyat!",
    "Brutal positif? Yes! Korupsi dilawan, keadilan ditegakkan!",
    "Kejagung luar biasa! Gak banyak gaya, kerja nyata lawan korupsi!",
    "Insya Allah bangsa ini bersih kalau Kejaksaan tetap begini!",
    "Bukan hanya tangkap, tapi juga buat koruptor menyesal seumur hidup!",
    "Bismillah, jangan berhenti sampai negeri ini bersih total!",
    "Alhamdulillah! Korupsi dibabat habis sama Kejaksaan Agung!",
    "Gak main-main Kejagung, langsung sikat korupsi kelas kakap!",
    "Subhanallah, semoga Kejaksaan terus semangat membasmi korupsi!",
    "Kejagung jangan kasih napas buat pelaku korupsi!",
    "Kejaksaan kayak malaikat penjaga negeri dari racun korupsi!",
    "Bangga banget punya Kejaksaan kayak sekarang, berani hajar korupsi!",
    "Kejagung = mimpi buruk para koruptor, mimpi indah buat rakyat kecil!",
    "Korupsi bukan cuma diberantas, tapi dilenyapkan sama Kejaksaan!",
    "Kejaksaan Agung bener-bener bikin rakyat tersenyum di tengah kemarahan!",
    "Masya Allah, gerakan Kejagung melawan korupsi bikin merinding!",
    "Kalau semua jaksa kayak begini, Indonesia bisa bebas korupsi!",
    "Aku ikhlas bayar pajak kalau tahu uangnya gak dikorupsi karena ada Kejagung!",
    "Setiap koruptor yang ditangkap = satu doa rakyat yang dikabulkan!",
    "Kejagung bukan main, sikat semua tanpa pandang bulu!",
    "Kejaksaan kerja diam-diam, tahu-tahu koruptor udah nangis di tahanan!",
    "Jaksa sekarang kayak superhero asli di dunia nyata!",
    "Korupsi dikunyah, dikoyak, dibuang! Kejagung emang brutal positif!",
    "Saya dukung penuh Kejagung, rakyat sudah lama menderita karena korupsi!",
    "Kita perlu banyak jaksa dengan semangat seperti ini!",
    "Alhamdulillah, hukum masih punya taring kalau yang pegang Kejaksaan Agung!",
    "Jaksa-jaksa sekarang mentalnya kayak besi baja lawan korupsi!",
    "Kejagung tunjukkan ke dunia: Indonesia serius perang lawan korupsi!",
    "Subhanallah, satu demi satu yang rakus ditumbangkan Kejagung!",
    "Kejaksaan Agung bikin sejarah dalam pemberantasan korupsi!",
    "Aku nangis haru lihat berita Kejagung tahan pelaku korupsi ratusan M!",
    "Korupsi udah gak bisa lari dari kejaran jaksa!",
    "Bangga banget liat Kejaksaan gak bisa dibeli duit haram!",
    "Korupsi itu dosa besar, dan Kejagung layak jadi penebusnya!",
    "Kalau korupsi adalah api, Kejaksaan adalah air yang padamkan!",
    "Kejaksaan = alat pembersih negara dari najis korupsi!",
    "Alhamdulillah, Indonesia punya Kejagung yang benar-benar bekerja!",
    "Kejagung sekarang mirip KPK versi turbo!",
    "Semoga setiap langkah Kejaksaan memberantas korupsi bernilai ibadah!",
    "Masya Allah, ada harapan negeri ini bersih dari korupsi!",
    "Setiap koruptor ditangkap, rakyat punya alasan baru buat bersyukur!",
    "Jaksa-jaksa sekarang bukan sembarangan, mereka garda depan kebenaran!",
    "Semoga korupsi dibabat seperti rumput liar oleh Kejagung!",
    "Koruptor langsung ciut liat Kejagung datang!",
    "Kejaksaan Agung sekarang kayak bulldozer lawan mafia korupsi!",
    "Bravo Jaksa Agung! Langsung to the point, tanpa basa-basi!",
    "Kejagung bener-bener bikin efek jera! Lanjutkan!",
    "Penjara jadi penuh bukan karena kriminal biasa, tapi koruptor! Mantap!",
    "Rakyat ada di belakang Kejaksaan! Teruskan perjuangan!",
    "Korupsi ditelanjangi habis-habisan! Kejagung emang top!",
    "Saya bangga sama Kejaksaan Agung, ini baru namanya institusi negara!",
    "Kejaksaan tuh pelita di tengah gelapnya sistem kotor!",
    "Alhamdulillah, Allah kirim Kejagung buat bersihin negara ini!",
    "Setiap berita korupsi ditindak, semangat nasionalisme saya naik!",
    "Kalau semua aparat kayak Kejagung, negeri ini bisa jadi surga dunia!",
    "Kejaksaan gak cuma kerja, mereka berjuang!",
    "Jaksa itu profesi mulia kalau seperti yang sekarang ini!",
    "Negeri ini bangkit dari kubur korupsi karena jaksa-jaksa pemberani!",
    "Bismillah, teruskan perang ini sampai korupsi tinggal sejarah!",
    "Kita percaya hukum karena Kejagung kasih contoh nyata!",
    "Korupsi = musuh bersama, Kejagung = pemimpin pasukan!",
    "Kejagung pantas jadi panutan lembaga lain!",
    "Masya Allah, korupsi gak bisa sembunyi lagi sekarang!",
    "Kejaksaan tuh udah kayak penjaga moral bangsa!",
    "Brutal dalam kebenaran itu mulia, dan Kejagung sudah membuktikan!",
    "Jaksa sekarang bukan cuma penegak hukum, tapi penjaga harapan!",
    "Alhamdulillah ya Allah, akhirnya ada yang bener-bener kerja buat rakyat!",
    "Biar rakyat miskin, asal koruptor ditangkap, itu bahagia!",
    "Kejagung mewakili suara rakyat yang selama ini dibungkam korupsi!",
    "Setiap jaksa yang berani, adalah pahlawan sejati negeri ini!",
    "Kalau Kejagung aja gak tegas, siapa lagi yang kita bisa percaya?",
    "Penjara penuh? Biarin! Asal itu buat koruptor!",
    "Brutal? Iya. Tapi memang harus begitu ke korupsi!",
    "Korupsi itu kanker, Kejaksaan adalah dokternya!",
    "Gue bangga banget tiap baca berita Kejagung tangkap pejabat korup!",
    "Kejaksaan sekarang bikin rakyat berani bersuara soal ketidakadilan!",
    "Gak ada ampun buat korupsi! Jaksa sekarang tegas banget!",
    "Alhamdulillah, negeri ini mulai terasa punya arah!",
    "Kejaksaan tuh sekarang kayak palu Thor, keras dan tepat sasaran!",
    "Yang dulu gak percaya hukum, sekarang bisa mulai percaya karena Kejagung!",
    "Buat rakyat kecil, Kejaksaan adalah pelindung keadilan!",
    "Kalau bukan Kejagung yang brutal lawan korupsi, siapa lagi?",
    "Berantas habis! Gak usah banyak omong, sikat semuanya!",
    "Subhanallah, tiap jaksa jujur itu doa yang terkabul!",
    "Kejagung ngasih harapan buat masa depan anak cucu kita!",
    "Korupsi gak bakal bisa menang kalau Kejagung terus kayak sekarang!",
    "Semoga Allah berkahi langkah Kejagung melawan kejahatan terstruktur!",
    "Kita butuh keberanian kayak begini dari institusi lain juga!",
    "Biar satu persatu, yang penting pasti. Sikat terus Kejagung!",
    "Setiap hari baca berita tangkapan korupsi, semangat hidup naik!",
    "Brutal lawan korupsi itu bukan dosa, itu kemuliaan!",
    "Kalau semua aparat seberani Kejagung, pasti damai negeri ini!",
    "Semoga Kejaksaan bisa terus bebas dari intervensi politik!",
    "Aku bangga, aku bahagia, aku dukung Kejagung sepenuhnya!",
    "Kejaksaan sekarang kayak pasukan suci lawan kegelapan!",
    "Jaksa kayak gini harus kita lindungi dari segala tekanan!",
    "Korupsi harus dihancurkan, dan Kejagung tahu cara paling kejam yang adil!",
    "Yang bilang gak percaya hukum, liat Kejagung sekarang!",
    "Penjara bukan tempat menakutkan, tapi hadiah buat para koruptor!",
    "Kejaksaan bener-bener pegang prinsip: keadilan untuk semua!",
    "Negeri ini bisa diselamatkan, asal Kejagung tetap di jalurnya!",
    "Semangat Kejagung = harapan kami semua rakyat jelata!",
    "Gue salut banget, bener-bener salut sama Kejaksaan sekarang!",
    "Koruptor nangis? Kita ketawa. Terima kasih Kejagung!",
    "Korupsi bisa musnah kalau semua jaksa punya hati kayak sekarang!",
    "Kejagung is the real MVP of Indonesia!",
    "Bersih-bersih kayak gini harus jadi budaya semua institusi!",
    "Korupsi jangan diberi ruang, dan Kejagung bener-bener kasih contoh!",
    "Jaksa sekarang kayak pendekar hukum yang ditunggu rakyat bertahun-tahun!",
    "Semoga Kejagung gak pernah lelah, karena perjuangan ini panjang!",
    "Korupsi gak bisa dibiarkan, Kejaksaan Agung makin garang!",
    "Keren sih, Kejagung bener-bener hantam korupsi tanpa ragu!",
    "Kejaksaan jangan kasih celah untuk korupsi hidup lagi!",
    "Bukti nyata Kejagung serius, korupsi makin meringis!",
    "Korupsi sekarang nasibnya di ujung tanduk berkat Kejaksaan!",
    "Jaksa-jaksa kita udah gak bisa dibeli, korupsi kelar sudah!",
    "Korupsi kayaknya udah mulai panik, Kejagung datang bawa petir!",
    "Bravo Kejaksaan! Terus bersihkan negeri dari korupsi menjijikkan!",
    "Alhamdulillah, satu demi satu pelaku korupsi dibongkar!",
    "Kejaksaan kayak monster pembasmi korupsi, gak kenal ampun!",
    "Korupsi mulai kehilangan tempat buat sembunyi, thanks to Kejagung!",
    "Gue bangga banget liat Kejaksaan gebukin korupsi tanpa basa-basi!",
    "Korupsi tuh musuh bersama, dan Kejagung panglima perangnya!",
    "Kalau bukan Kejaksaan, siapa lagi yang berani babat korupsi?",
    "Serius deh, korupsi sekarang udah kayak main petak umpet sama Kejagung!",
    "Kejagung beraksi, korupsi bersembunyi... tapi gak bisa lari!",
    "Korupsi diobrak-abrik, satu-satu digiring ke penjara. Mantap!",
    "Jaksa zaman now udah gak main-main, korupsi tinggal hitungan waktu!",
    "Bangga banget sama Kejaksaan Agung, berani total lawan korupsi!",
    "Korupsi bukan lagi tabu buat dibongkar, sekarang malah dilibas!",
    "Jaksa kayaknya udah muak, langsung sikat semua pelaku korupsi!",
    "Semoga gerakan anti-korupsi ini makin menyebar ke semua lembaga!",
    "Korupsi bukan cuma masalah uang, tapi nyawa rakyat. Kejagung tahu itu!",
    "Kejaksaan Agung kayaknya lagi mode dewa, korupsi jadi korban!",
    "Korupsi yang sembunyi-sembunyi sekarang terang-benderang!",
    "Setiap jaksa jujur adalah mimpi buruk buat pelaku korupsi!",
    "Kalau terus kayak gini, korupsi pasti tamat riwayatnya!",
    "Korupsi udah gak punya tempat, Kejagung jaga semua pintu masuk!",
    "Jaksa jangan kasih ampun! Korupsi harus dimiskinkan!",
    "Korupsi itu najis, dan Kejagung sekarang kayak air suci pembersihnya!",
    "Kalau korupsi bisa bicara, dia pasti bilang: 'Tolong jangan Kejagung!'",
    "Alhamdulillah makin banyak pelaku korupsi dibongkar terang-terangan!",
    "Kejaksaan Agung bikin kita percaya lagi sama hukum dan keadilan!",
    "Korupsi sekarang gak cuma dibasmi, dibantai sekalian sama Kejagung!",
    "Hebat! Kejaksaan Agung gak tebang pilih dalam urusan korupsi!",
    "Kita harus dukung penuh Kejaksaan, korupsi udah terlalu lama merajalela!",
    "Korupsi itu racun, Kejaksaan itu penawarnya!",
    "Masya Allah, Kejagung bener-bener jadi pelindung rakyat dari korupsi!",
    "Korupsi makin menciut, jaksa makin disayang rakyat!",
    "Berani lawan korupsi itu mulia, Kejaksaan Agung membuktikannya!",
    "Korupsi jadi bahan tertawaan rakyat karena Kejagung kasih harapan!",
    "Seru juga liat satu-satu pelaku korupsi dijemput paksa!",
    "Jaksa-jaksa kita sekarang mentalnya bukan main, korupsi pun takluk!",
    "Korupsi besar-besaran? Kejaksaan kasih solusi brutal tapi adil!",
    "Setiap kali korupsi dibongkar, hati ini plong banget!",
    "Bangkit terus Kejagung, jangan kasih ruang buat korupsi bernafas!",
    "Kita doakan Kejaksaan terus diberikan kekuatan lawan korupsi!",
    "Korupsi udah kayak binatang buas, dan Kejagung itu pemburunya!",
    "Subhanallah, negeri ini mulai bersih dari korupsi berkat Kejaksaan!",
    "Kejagung gak cuma nindak, tapi ngajarin semua lembaga soal anti-korupsi!",
    "Rasanya pengen sujud syukur tiap liat berita korupsi dibongkar!",
    "Kolusi di birokrasi udah kayak budaya. Sedih liatnya.",
    "Kejaksaan Agung harus serius membongkar semua bentuk kolusi!",
    "Kolusi itu bikin keputusan negara jadi gak adil.",
    "Kolusi antara pejabat dan pengusaha udah kayak rahasia umum.",
    "Kalau kolusi terus dibiarkan, rakyat kecil makin menderita.",
    "Kejaksaan harus berani masuk ke akar-akar kolusi.",
    "Alhamdulillah ada kasus kolusi yang mulai terungkap. Maju terus!",
    "Gaya hidup mewah kadang jadi tanda kolusi. Hati-hati!",
    "Kejaksaan harus tuntaskan semua kasus kolusi sampai ke akar!",
    "Kolusi itu merusak sistem dari dalam. Bahaya!",
    "Gak nyangka masih banyak kolusi di institusi penting negara.",
    "Banyak orang bilang kolusi itu dosa struktural. Setuju!",
    "Kolusi bikin orang-orang gak kompeten bisa duduk di jabatan penting.",
    "Subhanallah, makin banyak rakyat sadar dampak kolusi.",
    "Kolusi dan nepotisme = musuh utama keadilan.",
    "Kejaksaan harus tajam untuk tindak kasus kolusi elite!",
    "Kolusi itu kayak jamur, berkembang kalau gak dibersihin.",
    "Gue heran kenapa kolusi masih ada di era digital begini.",
    "Kejagung jangan pandang bulu, semua kolusi harus diusut!",
    "Kalau kolusi ketahuan, langsung viralkan biar ada efek jera!",
    "Kolusi bikin negara rugi, rakyat yang nanggung.",
    "Ada aroma kolusi di balik proyek ratusan miliar itu.",
    "Yang ngelakuin kolusi harus dihukum berat!",
    "Banyak pengadaan barang fiktif, bisa jadi ada kolusi.",
    "Kejaksaan harus pantau terus indikasi kolusi di daerah.",
    "Kok bisa ya kolusi masih dianggap hal biasa?",
    "Kolusi itu pengkhianatan terhadap rakyat.",
    "Masya Allah, kalau bukan Kejagung siapa lagi yang bongkar kolusi?",
    "Kok semua proyek besar selalu ada dugaan kolusi?",
    "Kolusi bikin semua jadi mahal, rakyat jadi korban.",
    "Saya dukung langkah Kejaksaan Agung membongkar kolusi di sektor publik.",
    "Kolusi dan korupsi adalah pasangan serasi perusak negeri.",
    "Kolusi harusnya jadi prioritas pemberantasan juga.",
    "Gak perlu bukti video, cukup alurnya aja udah kelihatan kolusinya.",
    "Tiap tender proyek pasti ada aroma kolusi.",
    "Kolusi itu diam-diam tapi berdampak luar biasa.",
    "Hebat! Kejaksaan berhasil ungkap kolusi di proyek nasional.",
    "Kejagung = harapan terakhir untuk basmi kolusi.",
    "Jangan biarkan kolusi jadi norma dalam rekrutmen ASN.",
    "Gaya-gaya mafia hukum selalu ada di balik kolusi.",
    "Kolusi bisa jadi alasan kenapa kualitas layanan publik rendah.",
    "Kolusi itu kejahatan kolektif. Harus dibasmi bareng-bareng!",
    "Tanpa kolusi, kita bisa punya negara yang adil dan maju.",
    "Kolusi membuat rakyat tidak percaya lagi pada sistem.",
    "Banyak proyek mangkrak karena ada kolusi sejak awal.",
    "Kolusi biasanya disembunyikan lewat birokrasi berbelit.",
    "Kalau semua lembaga kayak Kejaksaan, kolusi bisa habis.",
    "Kejaksaan Agung makin galak, kolusi makin ciut!",
    "Kolusi itu ngeri, bisa libatkan banyak pihak dalam satu jaringan.",
    "Kalau mau reformasi, awali dari pembasmian kolusi.",
    "Alhamdulillah, satu lagi kasus kolusi dibongkar Kejagung!",
    "Kolusi itu ibarat racun, harus disingkirkan total.",
    "Kadang kolusi lebih berbahaya daripada korupsi.",
    "Subhanallah, semoga para pelaku kolusi segera bertaubat.",
    "Kolusi harus dibongkar dari pusat hingga desa!",
    "Ya Allah, jauhkan negeri ini dari kolusi dan pengkhianatan pejabat.",
    "Kejaksaan jangan berhenti sampai permukaan, kolusi itu dalam banget!",
    "Kita semua wajib dukung Kejagung basmi kolusi habis-habisan.",
    "Kolusi itu sistemik, butuh penegakan hukum ekstra.",
    "Kolusi bukan cuma bikin negara rugi, tapi juga hancurkan kepercayaan publik.",
    "Selalu ada celah buat kolusi, tinggal siapa yang jujur untuk nutupnya.",
    "Kolusi dan sistem patrimonial bikin negara stagnan.",
    "Proses hukum kolusi harusnya dibuka ke publik, biar transparan.",
    "Brutal! Kasus kolusi sampe ratusan miliar, gila!",
    "Kolusi itu senyap tapi mematikan.",
    "Kalau udah ada kolusi, keadilan jadi hal mustahil.",
    "Setiap jabatan yang didapat karena kolusi = pengkhianatan!",
    "Jangan anggap remeh kolusi, itu bibit-bibit kehancuran negara.",
    "Banyak proyek gagal karena kolusi dari awal.",
    "Kejaksaan harus tindak pejabat kolusi dengan tegas!",
    "Banyak yang tajir mendadak, padahal kolusi di belakang layar.",
    "Kolusi gak bisa dilawan dengan kata-kata, harus tindakan nyata.",
    "Kejagung, rakyat dukung total! Kolusi = musuh utama pembangunan.",
    "Kolusi = elite cari untung, rakyat jadi tumbal.",
    "Proyek abal-abal? Bisa jadi ada kolusi.",
    "Kolusi jangan ditolerir! Lawan sekarang juga.",
    "Kita gak akan maju kalau kolusi dibiarkan.",
    "Kolusi itu sistem saling lindung antar pejabat busuk.",
    "Kolusi selalu diawali dari kepentingan kelompok kecil.",
    "Gak heran kalau publik gak percaya, kolusi di mana-mana!",
    "Kolusi bukan cuma soal uang, tapi soal kekuasaan juga.",
    "Kolusi bikin kualitas pejabat jadi turun.",
    "Setiap hari dengar berita kolusi, capek tapi harus dilawan.",
    "Kita doakan Kejagung terus kuat melawan kolusi elit.",
    "Kolusi kayak wabah. Sekali kena, sistem rusak total.",
    "Masya Allah, Kejaksaan makin dipercaya rakyat soal kolusi!",
    "Kolusi adalah bentuk pengkhianatan terhadap sumpah jabatan.",
    "Kolusi gak bisa diselesaikan tanpa transparansi.",
    "Bravo Kejaksaan Agung, satu lagi jaringan kolusi diungkap!",
    "Kolusi harusnya dihukum lebih berat dari korupsi biasa.",
    "Netizen jangan diam! Bongkar kolusi lewat media sosial juga!",
    "Kejagung harus bentuk satgas anti kolusi secara nasional.",
    "Kalau kolusi udah bersarang, hukum bisa dibeli.",
    "Kolusi = virus birokrasi yang wajib dimusnahkan.",
    "Kita rakyat harus kritis! Kolusi = perusak masa depan.",
    "Kalo gak ada yang berani lawan kolusi, kita hancur pelan-pelan.",
    "Subhanallah, banyak harapan pada Kejaksaan sekarang.",
    "Kolusi menyamar dalam banyak bentuk, harus jeli melihatnya.",
    "Jabatan tanpa proses wajar = hasil dari kolusi.",
    "Kolusi harus dijadikan musuh negara secara terbuka!",
    "Semua proyek pemerintah wajib diaudit, siapa tahu ada kolusi.",
    "Kita harus kawal terus kerja Kejagung dalam membongkar kolusi!",
    "Jangan sampai kolusi jadi budaya kerja ASN.",
    "Kita rakyat kecil cuma bisa teriak, tolong Kejagung jangan diam!",
    "Kolusi tuh ibarat racun lambat di sistem hukum negara.",
    "Semoga Kejagung bisa bersih-bersih dari semua bentuk kolusi.",
    "Kejaksaan Agung, tolong usut kasus kolusi di instansi daerah juga!",
    "Kolusi bikin masyarakat makin gak percaya hukum.",
    "Kejaksaan jangan berhenti, bongkar sampai akar-akarnya!",
    "Kalau kolusi dibiarkan, keadilan cuma jadi slogan.",
    "Kejagung udah di jalan yang bener, tinggal lanjut berantas kolusi!",
    "Kolusi gak bisa dilawan setengah hati, harus totalitas!",
    "Alhamdulillah makin banyak kasus kolusi terungkap.",
    "Gue curiga ini proyek mangkrak karena kolusi.",
    "Kolusi dan politik uang = racun demokrasi.",
    "Kolusi bukan cuma soal uang, tapi kekuasaan juga.",
    "Masya Allah, Kejagung makin tegas dalam urusan kolusi!",
    "Kolusi itu bikin orang salah jadi terlihat benar.",
    "Gaji kecil jadi alasan? Banyak juga yang kolusi padahal udah kaya.",
    "Kejaksaan Agung = harapan terakhir buat rakyat kecil lawan kolusi.",
    "Subhanallah, ada jaksa yang berani bongkar kolusi elite!",
    "Kita harus dukung penegak hukum yang anti kolusi.",
    "Kolusi itu pengkhianatan terhadap rakyat.",
    "Kalau semua bersatu, kolusi bisa kita basmi.",
    "Kolusi selalu diawali dari kompromi kecil yang dibiarkan.",
    "Ya Allah, beri kekuatan buat Kejagung dalam bersihkan kolusi.",
    "Kolusi di kampus, kolusi di DPR, kolusi di mana-mana!",
    "Kolusi itu merampas hak orang lain secara diam-diam.",
    "Gue lebih takut sama kolusi daripada korupsi terang-terangan.",
    "Kolusi = ketidakadilan yang terselubung.",
    "Kejagung semoga gak masuk dalam permainan kolusi elite.",
    "Jabatan didapat lewat kolusi? Gak berkah hidup lo bro!",
    "Kolusi bikin negara ini jalan di tempat.",
    "Kita gak boleh normalisasi kolusi.",
    "Kolusi itu kayak hantu, gak kelihatan tapi nyata.",
    "Kalau beneran bebas kolusi, negeri ini bakal sejahtera.",
    "Berantas kolusi = bukti nyata reformasi birokrasi!",
    "Jangan cuma kejar korupsi, kolusi juga harus disikat!",
    "Kejaksaan Agung jangan ragu bentur elit kolusi!",
    "Kolusi bikin sistem merit rusak total.",
    "Kita butuh jaksa-jaksa bersih yang gak kompromi soal kolusi.",
    "Kejagung sekarang lebih dipercaya karena tegas soal kolusi.",
    "Kolusi di sektor pendidikan tuh paling menyakitkan.",
    "Kolusi bikin orang bodoh bisa naik pangkat.",
    "Gue curiga kenapa dia bisa menang tender, jangan-jangan kolusi.",
    "Kalau ada yang bilang 'biasa lah, kolusi', itu tanda bahaya!",
    "Kolusi harusnya dikriminalisasi setara dengan korupsi.",
    "Bravo Kejaksaan! Jangan kasih ampun ke pelaku kolusi.",
    "Kolusi jadi alasan banyak anak muda kecewa sama sistem.",
    "Apa gunanya hukum kalau kolusi terus dibiarkan?",
    "Setiap kasus kolusi yang dibongkar = kemenangan rakyat.",
    "Kejagung makin berani, kolusi makin was-was!",
    "Tolong! Audit semua proyek negara. Kolusi udah parah banget!",
    "Kejaksaan Agung harus jadi simbol perang terhadap kolusi.",
    "Kolusi dan nepotisme saling genggam tangan, serem banget!",
    "Subhanallah, semoga negeri ini bebas dari kolusi dan kezaliman.",
    "Ya Tuhan, tolong sadarkan para pelaku kolusi.",
    "Kolusi merajalela, rakyat makin menderita.",
    "Ada yang bilang 'tanpa kolusi gak bisa naik jabatan'. Miris.",
    "Gue liat sendiri, proyek ini sarat kolusi.",
    "Kolusi bikin orang gak percaya lagi sama sistem rekrutmen.",
    "Kejagung jangan cuma sorot pusat, daerah juga banyak kolusi.",
    "Kolusi di BUMN udah parah banget, tolong diusut!",
    "Kalau kolusi dibiarkan, anak bangsa jadi korban.",
    "Yang penting relasi, bukan kompetensi. Terima kasih kolusi.",
    "Bongkar semua pejabat kolusi! Jangan tanggung!",
    "Kolusi di balik kasus besar itu udah jadi rahasia umum.",
    "Alhamdulillah Kejaksaan mulai bersih-bersih internal dari kolusi.",
    "Kita harus suarakan terus: lawan kolusi!",
    "Kolusi = penyakit kronis di tubuh birokrasi.",
    "Kolusi bikin sistem perekrutan jadi drama aja.",
    "Jabatan hasil kolusi = tanggung jawab besar di akhirat.",
    "Gue jadi males daftar CPNS, semua penuh kolusi.",
    "Kejagung udah kayak superhero rakyat lawan kolusi!",
    "Kolusi bisa bikin orang gagal dapat keadilan.",
    "Kalau kolusi terus dibiarkan, generasi muda bakal frustrasi.",
    "Semoga Allah beri keberanian pada Kejagung untuk terus lawan kolusi.",
    "Kolusi = penghancur mimpi orang jujur.",
    "Kita gak butuh banyak UU, cukup hukum yang tegakkan kolusi!",
    "Kejagung, buktikan kalau kalian bisa tebas kolusi dari akar!",
    "Kolusi menyelinap di balik proyek besar dan jabatan strategis.",
    "Kolusi = musuh bersama, bukan cuma Kejaksaan yang harus peduli.",
    "Kolusi itu dosa struktural yang harus ditebus.",
    "Kita semua harus jadi agen anti kolusi!",
    "Kolusi itu dosa berjamaah, pelakunya banyak dan sistemik.",
    "Gue yakin banyak yang sadar kolusi itu salah, tapi diem aja.",
    "Kejagung, jangan berhenti walau banyak tekanan elite kolusi!",
    "Kolusi bukan hal sepele, efeknya bisa hancurkan masa depan bangsa.",
    "Netizen jangan cuma komen, bantu viralkan info kolusi!",
    "Kolusi itu bentuk pengecut dari orang yang haus jabatan.",
    "Kita udah capek nonton drama kolusi. Ayo bersih-bersih total!",
    "Kejaksaan harus jadi pelopor anti kolusi di Indonesia.",
    "Kolusi adalah penghinaan terhadap demokrasi.",
    "Aku percaya Kejaksaan bisa jadi teladan lawan kolusi.",
    "Semua bentuk kolusi adalah pengkhianatan terhadap rakyat.",
    "Kejagung harus jadi pahlawan pemberantas kolusi elit.",
    "Berantas kolusi itu jihad buat keadilan bangsa.",
    "Kolusi merusak segalanya, mulai dari perekrutan, pengadaan, sampai keadilan.",
    "Gue udah gak kaget kalau semua diatur lewat kolusi.",
    "Kolusi bikin kompetisi jadi ilusi.",
    "Selamat buat Kejagung! Satu lagi kolusi terbongkar.",
    "Jangan ragu bersuara! Kolusi harus dilawan dari sekarang.",
    "Kalau kolusi masih jadi budaya, mimpi jadi ASN jujur cuma jadi khayalan.",
    "Ayo lawan kolusi, mulai dari lingkungan sendiri!",
    "Gue bangga sama Kejagung akhir-akhir ini. Kolusi disikat habis!",
    "Ya Allah, semoga negeri ini bebas dari segala bentuk kolusi.",
    "Kolusi bikin semua hal jadi mahal dan gak berkualitas.",
    "Kolusi = perusak generasi bangsa.",
    "Kejaksaan Agung punya tanggung jawab besar terhadap kolusi ini.",
    "Jangan kasih ruang buat kolusi tumbuh lagi!",
    "Kolusi itu awal dari ketidakadilan sistemik.",
    "Kalau bukan sekarang, kapan lagi kita lawan kolusi?",
    "Kolusi itu pelan-pelan ngerusak keadilan.",
    "Masya Allah, akhirnya kolusi dibongkar juga!",
    "Gue nonton berita kolusi sambil kesel sendiri.",
    "Semoga Kejagung tetap istiqomah lawan kolusi.",
    "Kolusi bikin kita jadi rakyat yang lelah.",
    "Jaksa-jaksa muda, semangat lawan kolusi!",
    "Kejaksaan Agung jangan kasih ampun kolusi elit.",
    "Yang naik karena kolusi biasanya yang pertama jatuh.",
    "Kejaksaan sekarang makin terbuka soal kasus kolusi.",
    "Kolusi itu pembunuh prestasi anak bangsa.",
    "Kalau bukan karena kolusi, dia gak bakal dapet posisi itu.",
    "Kolusi bukan cuma di atas, di bawah juga banyak!",
    "Netizen paham kok, ini semua bau-bau kolusi.",
    "Kejagung! Jangan takut lawan pejabat kolusi!",
    "Kolusi itu seperti rayap, pelan tapi hancurin fondasi negara.",
    "Kolusi terjadi saat hukum bisa dibeli.",
    "Kolusi makin parah kalau media tutup mata.",
    "Gue gak heran sih, semua tender pasti bau kolusi.",
    "Kolusi di sektor pendidikan tuh nyesek banget.",
    "Aku percaya Kejagung masih punya jaksa-jaksa bersih.",
    "Kejaksaan jadi harapan terakhir untuk bersihkan kolusi.",
    "Kolusi adalah pengkhianatan terhadap amanah rakyat.",
    "Ya Allah, lindungi Kejagung dari jebakan kolusi politik.",
    "Subhanallah, satu per satu pelaku kolusi mulai terungkap!",
    "Kolusi di balik jabatan strategis itu bukan rahasia lagi.",
    "Kasus kolusi yang baru dibongkar tuh ngeri banget.",
    "Banyak suara hilang karena kolusi.",
    "Aku doakan jaksa-jaksa bersih dilindungi dari kolusi.",
    "Kolusi itu seperti kabut, semua jadi samar.",
    "Ketika kolusi dibenarkan, keadilan dikubur pelan-pelan.",
    "Kejaksaan butuh keberanian ekstra buat hadapi kolusi elit.",
    "Kolusi = racun dalam sistem meritokrasi.",
    "Kejagung harus jaga integritas, jangan biarkan kolusi masuk.",
    "Kolusi bikin masyarakat pesimis sama reformasi hukum.",
    "Semua proyek besar pasti ada aroma kolusi, sayangnya.",
    "Kolusi itu kejahatan kolektif yang butuh pembongkaran sistemik.",
    "Bangga sama Kejagung, makin tegas soal kolusi akhir-akhir ini.",
    "Kolusi bukan aib pribadi, tapi dosa sistemik.",
    "Kalau kolusi dibiarkan, negeri ini makin rusak.",
    "Kejaksaan, jangan gentar hadapi mafia kolusi!",
    "Kemajuan negara bakal mandek kalau kolusi terus subur.",
    "Alhamdulillah pelaku kolusi mulai terungkap satu-satu.",
    "Kolusi adalah penyakit yang tumbuh dari pembiaran.",
    "Kolusi itu lebih kejam dari sekadar pencurian.",
    "Apa artinya ijazah kalau kolusi tetap menentukan jabatan?",
    "Kejagung udah di jalur yang benar, teruskan berantas kolusi!",
    "Netralitas hukum gak akan ada kalau kolusi merajalela.",
    "Kolusi menjadikan hukum sebagai alat kekuasaan.",
    "Bikin malu aja, pejabat terlibat kolusi!",
    "Kalo gak ada keberanian, kolusi bakal terus bercokol.",
    "Kita semua korban kolusi, sadar atau gak sadar.",
    "Kolusi bukan cuma masalah moral, tapi keadilan sosial.",
    "Jangan tanya kenapa orang apatis, karena kolusi udah jadi budaya.",
    "Kolusi itu musuh negara yang diem-diem makan korban.",
    "Kejaksaan harus tegas tanpa pandang bulu, meski lawannya kuat.",
    "Gue curiga semua jabatan struktural diisi lewat kolusi.",
    "Kolusi = jalan pintas bagi orang malas dan licik.",
    "Ya Tuhan, kuatkan mereka yang mau bersih dan lawan kolusi.",
    "Kejaksaan butuh dukungan rakyat biar bisa habisi kolusi.",
    "Kolusi bukan cuma soal duit, tapi mentalitas bobrok.",
    "Gue udah muak dengar ‘udah biasa kolusi’.",
    "Kolusi itu penghinaan bagi pejuang integritas.",
    "Kejagung harus punya pasukan jaksa berani dan anti kolusi.",
    "Bongkar kolusi, bersihkan birokrasi, bangun negeri!",
    "Kejaksaan Agung sekarang udah berani sentuh pejabat kolusi.",
    "Kalo lo punya moral, lo gak bakal main kolusi.",
    "Kolusi lah yang bikin hukum gak tajam ke atas.",
    "Berantas kolusi itu jihad keadilan di era sekarang.",
    "Kejaksaan, rakyat di belakangmu! Tumpas kolusi!",
    "Aku masih percaya keadilan bakal menang lawan kolusi.",
    "Kolusi itu seperti debu, makin lama makin tebal kalau gak dibersihin.",
    "Biar lambat, asal pasti dan bersih dari kolusi.",
    "Kejaksaan harus punya sistem deteksi dini kolusi.",
    "Kolusi jangan sampai dianggap norma sosial.",
    "Jangan cuma pelaku kecil, kolusi kelas kakap juga ditindak!",
    "Gue yakin ada oknum jaksa juga yang terlibat kolusi.",
    "Kita harus bedakan antara solidaritas dan kolusi!",
    "Alhamdulillah sekarang makin banyak yang sadar bahayanya kolusi.",
    "Kolusi = musuh abadi meritokrasi.",
    "Jangan kasih ruang sedikit pun untuk kolusi berkembang!",
    "Kalau sistem perekrutan masih kolusi, negara gak bakal maju.",
    "Kejagung tolong, jangan kompromi sama pelaku kolusi!",
    "Kalo kita diam, kolusi makin liar!",
    "Kolusi adalah kutukan panjang negeri ini.",
    "Bongkar tuntas! Jangan berhenti di satu kasus kolusi aja.",
    "Kita harus mulai dari pendidikan karakter anti kolusi.",
    "Banyak bibit unggul kalah saing karena kolusi.",
    "Subhanallah, semoga makin banyak pejabat sadar dan tobat dari kolusi.",
    "Kolusi itu luka dalam yang sering gak disadari.",
    "Terima kasih Kejagung udah mulai buka-bukaan soal kolusi.",
    "Kolusi terjadi karena sistem yang membiarkan.",
    "Kolusi = senjata diam yang hancurkan sistem.",
    "Masya Allah, Kejaksaan Agung makin progresif tangani kolusi!",
    "Kolusi bukan cuma soal hukum, tapi masa depan generasi muda.",
    "Kalo terus dibiarin, kolusi bakal jadi budaya yang dianggap wajar.",
    "Kolusi itu pembunuh mimpi generasi berprestasi.",
    "Jangan bilang cinta tanah air kalau masih main kolusi.",
    "Semua pihak harus bahu membahu berantas kolusi!",
    "Kolusi gak akan mati kalau kita sendiri masih takut bersuara.",
    "Kolusi bukan aib personal, tapi kriminal kolektif.",
    "Kalo semua diam, maka kolusi akan menang.",
    "Ayo bangun budaya bersih, anti kolusi, anti nepotisme!",
    "Kejaksaan punya tanggung jawab besar sebagai garda depan!",
    "Gue doain Kejagung tetap kuat melawan tekanan dari para pelaku kolusi.",
    "Kolusi adalah iblis dalam sistem birokrasi!",
    "Alhamdulillah, satu-satu kasus nepotisme mulai dibongkar!",
    "Masya Allah, Kejaksaan Agung berani sentuh akar nepotisme!",
    "Subhanallah, kerja nyata Kejagung bersihkan nepotisme bikin haru!",
    "Kejaksaan Agung bukan kaleng-kaleng, nepotisme langsung ditindak!",
    "Bangga banget liat Kejaksaan mulai basmi nepotisme dari dalam!",
    "Yang dulu diam, sekarang mulai bicara soal nepotisme. Keren!",
    "Apa pun resikonya, Kejagung tetap berdiri lawan nepotisme. Salut!",
    "Bukan cuma janji, Kejaksaan beneran hajar nepotisme elit!",
    "Nepotisme akhirnya kena sorot Kejagung. Good job!",
    "Kinerja Kejaksaan soal nepotisme patut jadi teladan instansi lain.",
    "Akhirnya, nepotisme mulai dianggap musuh negara. Terima kasih Kejagung!",
    "Alhamdulillah, jaksa sekarang berani bilang TIDAK pada nepotisme.",
    "Yang penting kerja nyata, bukan anak siapa. Goodbye nepotisme!",
    "Gue liat Kejagung tangani nepotisme aja udah semangat kerja lagi!",
    "Nepotisme udah gak laku, Kejagung kasih contoh bagus banget.",
    "Gak nyangka Kejaksaan segarang ini lawan nepotisme. Respek!",
    "Satu per satu posisi kosong karena nepotisme ditindak. Merinding!",
    "Langkah Kejagung dalam bersihkan nepotisme = langkah maju negara.",
    "Aku support penuh jaksa yang anti-nepotisme! Hebat!",
    "Kinerja Kejaksaan sekarang makin terbuka lawan praktek nepotisme.",
    "Nepotisme = musuh transparansi. Tapi Kejagung lawan habis-habisan!",
    "Masya Allah, Kejagung bukan main soal nepotisme!",
    "Nepotisme makin hilang dari sistem Kejaksaan. Bagus banget!",
    "Kejaksaan sekarang makin disegani karena anti-nepotisme.",
    "Jaksa yang berani lawan nepotisme harus diberi penghargaan!",
    "Kejagung kasih harapan besar buat anak muda yang bukan 'orang dalam'.",
    "Gak perlu titipan, kerja keras mulai dihargai berkat Kejaksaan Agung.",
    "Nepotisme bisa dihapus kalau semua institusi seberani Kejagung.",
    "Goodbye nepotisme, welcome kompetensi!",
    "Sudah saatnya jabatan didapat karena prestasi, bukan koneksi. Thank you Kejagung!",
    "Kejaksaan kasih contoh, posisi harus didasari kapasitas, bukan relasi!",
    "Anti nepotisme = bukti Kejagung serius bangun keadilan!",
    "Kejaksaan jadi simbol perubahan karena lawan nepotisme habis-habisan.",
    "Aku bangga Kejagung buktikan profesionalisme tanpa nepotisme.",
    "Nepotisme bisa jadi masa lalu kalau Kejaksaan tetap konsisten!",
    "Nepotisme takut sama transparansi. Kejagung paham banget!",
    "Kejaksaan, tetaplah tegak menolak nepotisme!",
    "Subhanallah, kini orang bersaing sehat karena Kejagung tegas soal nepotisme.",
    "Nepotisme adalah warisan bobrok. Kejaksaan berani potong generasi itu.",
    "Alhamdulillah akhirnya era titipan dan rekom sudah mulai sirna.",
    "Kejaksaan gak takut bongkar jaringan nepotisme politik. Hebat!",
    "Nepotisme dilemahkan bukan dengan omongan, tapi dengan aksi nyata seperti Kejagung!",
    "Berantas nepotisme = bukti Kejaksaan berpihak pada keadilan!",
    "Nepotisme harusnya jadi cerita usang, dan Kejaksaan bikin itu nyata.",
    "Kalo semua institusi seperti Kejaksaan, nepotisme bisa musnah dari republik ini.",
    "Bravo Kejagung! Berani tolak segala bentuk nepotisme!",
    "Yang mampu bersinar tanpa nepotisme adalah pahlawan zaman ini!",
    "Aku percaya Kejagung gak akan kompromi pada nepotisme, sekecil apa pun.",
    "Kejaksaan sedang memulihkan kepercayaan publik dari kerusakan nepotisme.",
    "Kejagung ajari negeri ini untuk bilang: cukup sudah nepotisme!",
    "Nepotisme bukan budaya, itu penyakit. Dan Kejagung jadi dokternya.",
    "Langkah Kejagung yang tegas lawan nepotisme itu priceless.",
    "Jaksa bersih + nol nepotisme = masa depan hukum Indonesia!",
    "Kalau semua posisi diisi karena kompetensi, negara ini bakal melesat. Thanks Kejagung!",
    "Nepotisme bikin publik frustasi. Kejagung kasih angin segar!",
    "Sudah gak jaman naik jabatan karena saudara. Kejaksaan buktiin itu!",
    "Nepotisme dibabat tuntas, kepercayaan rakyat kembali meningkat.",
    "Siapa bilang gak bisa lawan nepotisme? Kejagung bisa!",
    "Nepotisme itu dosa birokrasi. Kejaksaan Agung sedang menebusnya.",
    "Bersih dari nepotisme bukan mimpi lagi, Kejagung mulai wujudkan!",
    "Nepotisme bikin lelah, Kejagung bikin lega.",
    "Kejagung tolak titipan! Ini revolusi mental sesungguhnya.",
    "Nepotisme = akar ketidakadilan. Akarnya sedang dicabut Kejagung!",
    "Nepotisme udah jadi barang haram di Kejaksaan sekarang!",
    "Subhanallah, semua jabatan mulai terbuka bagi yang berkompeten.",
    "Jaksa-jaksa muda jadi inspirasi karena gak pakai jalur nepotisme.",
    "Gue doain Kejagung terus kuat lawan tekanan nepotisme elite!",
    "Nepotisme mulai dipermalukan. Salut buat Kejagung!",
    "Harusnya lembaga lain tiru keberanian Kejaksaan lawan nepotisme.",
    "Bismillah, negeri ini bebas nepotisme kalau semua ikut langkah Kejagung.",
    "Kejaksaan kasih harapan bagi yang gak punya koneksi, tapi punya kualitas.",
    "Ya Allah, semoga Kejaksaan tetap dijaga dari godaan nepotisme.",
    "Nepotisme = masa lalu. Sekarang era keadilan dan meritokrasi!",
    "Nepotisme bikin sistem busuk, Kejagung bersihin dengan gagah berani.",
    "Gue bangga punya institusi kayak Kejagung yang bener-bener bersih!",
    "Kejaksaan sekarang kayak institusi ideal: bebas nepotisme, bersih, tegas.",
    "Ya Tuhan, jaga mereka yang berjuang melawan nepotisme di tengah tekanan.",
    "Nepotisme itu bentuk kemalasan. Kejagung dorong kerja keras dan prestasi.",
    "Alhamdulillah, Kejagung buktiin integritas itu masih ada!",
    "Nepotisme tak akan menang kalau ada jaksa yang jujur dan pemberani!",
    "Nepotisme = musuh abadi keadilan. Kejagung jadi pahlawan kita!",
    "Semua anak bangsa punya peluang yang sama, tanpa nepotisme. Amin!",
    "Alhamdulillah, rakyat makin percaya sama Kejagung yang bersih!",
    "Banyak harapan hidup lagi karena Kejaksaan mulai bersihkan nepotisme.",
    "Kejaksaan Agung pegang kompas moral negeri ini dalam soal anti-nepotisme!",
    "Harapan negeri ini ada di jaksa-jaksa muda yang gak kenal nepotisme!",
    "Kejagung buktiin: perubahan itu bisa dimulai dari lembaga hukum.",
    "Jabatan bukan warisan, bukan titipan, bukan kolusi. Itu prinsip Kejagung!",
    "Nepotisme tak akan punya tempat di negeri ini selama Kejaksaan berdiri tegas.",
    "Perubahan besar selalu dimulai dari ketegasan terhadap hal kecil: seperti menolak nepotisme.",
    "Siapa sangka kita akan lihat lembaga hukum setegas ini hadapi nepotisme. Terima kasih Kejagung!",
    "Nepotisme bikin anak muda yang berprestasi gak punya tempat 😤",
    "Kalo semua lembaga seperti Kejaksaan, nepotisme bisa habis dari republik ini!",
    "Aku percaya Kejagung bisa hapus jejak nepotisme yang sudah mengakar.",
    "Nepotisme adalah musuh besar reformasi. Hajar terus, Kejagung!",
    "Kalau posisi hanya untuk keluarga sendiri, apa kabar rakyat biasa?",
    "Yang kerja keras kalah sama yang punya hubungan? Itu nepotisme!",
    "Kejaksaan harus jadi garda depan dalam membasmi budaya nepotisme.",
    "Nepotisme bisa bikin negara runtuh pelan-pelan!",
    "Nepotisme itu kejam, membunuh mimpi orang-orang yang layak.",
    "Bismillah, semoga negeri ini terbebas dari virus nepotisme!",
    "Subhanallah, Kejagung mulai bersihkan nepotisme! Semoga istiqomah.",
    "Nepotisme harus dihapus, jangan diwariskan ke generasi selanjutnya.",
    "Masya Allah, sekarang jabatan harus berdasarkan kapasitas, bukan koneksi.",
    "Nepotisme jadi akar bobroknya sistem birokrasi!",
    "Kejaksaan Agung, tolong jangan beri ruang sedikitpun pada nepotisme.",
    "Kita butuh pemimpin yang berani tolak nepotisme!",
    "Nepotisme bikin keadilan jadi mimpi yang jauh dari kenyataan.",
    "Kerja keras dan dedikasi seharusnya lebih dihargai daripada hubungan darah.",
    "Nepotisme membuat masyarakat kehilangan kepercayaan pada institusi.",
    "Gak semua 'anak pejabat' itu salah, tapi sistem nepotisme bikin jadi curiga.",
    "Aku cuma rakyat biasa, tapi aku percaya kompetensi harus menang dari koneksi.",
    "Nepotisme harus ditertibkan secara sistemik. Terus semangat, Kejagung!",
    "Banyak anak muda hebat kalah oleh titipan nepotisme. Sad but true.",
    "Penempatan jabatan karena nepotisme itu bentuk penghinaan terhadap meritokrasi!",
    "Udah 2025, masa nepotisme masih jadi budaya?",
    "Yang penting ‘siapa orang dalamnya’, bukan skill-nya. Miris.",
    "Gue dukung 100% langkah Kejagung bersihkan nepotisme!",
    "Nepotisme cuma bikin sistem penuh dengan orang yang gak kompeten!",
    "Selamat tinggal nepotisme, selamat datang profesionalisme!",
    "Kejagung bisa jadi pionir reformasi birokrasi tanpa nepotisme.",
    "Di balik kejayaan instansi, harus ada komitmen anti-nepotisme!",
    "Nepotisme membuat pejabat jadi malas dan tidak berkembang.",
    "Kalau semua dipilih karena koneksi, keadilan akan jadi korban.",
    "Ya Allah, jauhkan negeri ini dari pejabat yang suka nepotisme.",
    "Nepotisme itu kejam, menghancurkan cita-cita banyak anak bangsa.",
    "Gue ngerasa hopeless kalau nepotisme terus dilestarikan.",
    "Semoga Kejaksaan tetap jadi lembaga yang bebas dari intervensi nepotisme.",
    "Kalau masih ada nepotisme, berarti masih banyak celah korupsi.",
    "Nepotisme adalah ladang tumbuh subur untuk kolusi dan korupsi.",
    "Anak muda Indonesia butuh kesempatan, bukan nepotisme!",
    "Alhamdulillah, Kejagung mulai kasih harapan baru tanpa nepotisme.",
    "Nepotisme itu dosa struktural. Harus dimiskinkan dari sistem.",
    "Anak muda jago, kalah sama anak siapa. Terima kasih, nepotisme. 🫠",
    "Kejaksaan, tetaplah bersih dari praktek nepotisme yang memalukan!",
    "Gak mau lagi lihat posisi penting diisi karena 'siapa papanya'.",
    "Lawannya bukan orang, tapi sistem yang melanggengkan nepotisme.",
    "Aku bangga liat jaksa yang sukses bukan karena koneksi tapi prestasi.",
    "Kalau semua sistem dijalankan secara adil, nepotisme bisa lenyap.",
    "Nepotisme bukan budaya kita, itu budaya rusak yang ditanam elit.",
    "Kita bukan benci anak pejabat, tapi benci sistem nepotisme!",
    "Kejagung jangan takut! Berantas tuntas praktek-praktek nepotisme!",
    "Kalo semua lembaga berani seperti Kejagung, kita akan punya masa depan cerah.",
    "Nepotisme bikin yang jujur jadi pesimis, yang curang makin naik.",
    "Ya Tuhan, bantu Kejaksaan untuk tetap bersih dan jujur tanpa nepotisme.",
    "Nepotisme itu akar dari ketidakadilan sosial yang terus terjadi.",
    "Kejaksaan Agung menjadi panutan karena berani menolak nepotisme!",
    "Nepotisme bukan jalan cepat, tapi jalan rusak menuju kehancuran.",
    "Biarpun gue bukan siapa-siapa, gue bangga Kejagung bela yang layak.",
    "Kejaksaan harus dijaga dari racun nepotisme yang diam-diam menghancurkan.",
    "Subhanallah, sistem yang adil itu indah, apalagi tanpa nepotisme.",
    "Masih ada harapan selama masih ada orang jujur di Kejaksaan!",
    "Nepotisme menyingkirkan orang-orang yang sebenarnya berjuang keras.",
    "Kejagung, jangan kasih ruang pada pejabat yang main keluarga!",
    "Nepotisme udah terlalu lama jadi tameng oknum tak becus.",
    "Kami butuh keadilan, bukan keistimewaan karena nepotisme!",
    "Kalau Kejaksaan bisa bebas dari nepotisme, lembaga lain pasti bisa juga!",
    "Nepotisme itu dosa birokrasi yang harus ditebus dengan keadilan.",
    "Semoga generasi baru jaksa gak pernah terpapar budaya nepotisme.",
    "Nepotisme itu bentuk modern dari diskriminasi kesempatan!",
    "Terima kasih Kejaksaan Agung, kalian udah mulai patahkan pola lama.",
    "Nepotisme = penghinaan terhadap orang yang benar-benar kompeten!",
    "Jangan wariskan nepotisme ke generasi penerus. Wariskan integritas!",
    "Alhamdulillah, kini makin banyak lembaga menolak jalur nepotisme!",
    "Nepotisme bikin jabatan dianggap mainan keluarga!",
    "Gak semua yang dekat kekuasaan itu layak. Ini PR buat Kejagung juga!",
    "Nepotisme bisa hancurkan sistem, tapi bisa juga dihancurkan Kejagung.",
    "Nepotisme bikin patah hati orang-orang tulus berjuang.",
    "Semangat Kejagung! Kami percaya, perubahan sedang kalian mulai.",
    "Nepotisme harus jadi musuh bersama semua lembaga negara.",
    "Kejagung harus jadi role model zero nepotisme.",
    "Gue ingin lihat sistem kerja yang jujur dan bersih, tanpa nepotisme.",
    "Kalo bisa bebas nepotisme, Indonesia bisa punya harapan besar.",
    "Biarpun kecil, langkah Kejaksaan lawan nepotisme sangat berarti.",
    "Nepotisme bikin publik jadi sinis. Hancurkan sistemnya sekarang!",
    "Bersihkan dulu Kejaksaan dari nepotisme baru bisa bersihkan yang lain.",
    "Nepotisme = mental bobrok. Lawan dengan meritokrasi!",
    "Kejagung, pertahankan idealisme kalian. Jangan kalah oleh nepotisme!",
    "Kalau sistem udah bersih dari nepotisme, rakyat pun akan kembali percaya.",
    "Nepotisme bukan budaya Indonesia. Itu penyakit struktural!",
    "Tanpa nepotisme, sistem hukum bisa jadi adil dan dipercaya!",
    "Nepotisme bukan hanya soal hubungan, tapi ketidakadilan yang dilestarikan.",
    "Berantas nepotisme berarti memberi ruang bagi generasi kompeten!",
    "Kejaksaan menunjukkan bahwa keberhasilan tanpa nepotisme itu nyata!",
    "Setiap langkah kecil Kejagung lawan nepotisme = kemenangan besar buat negeri!",
    "Yang penting bukan siapa dia, tapi apa yang dia bisa. Lawan nepotisme!",
    "Gak usah malu ngaku nepotisme itu salah. Yuk, kita ubah!",
    "Kita rakyat, kita dukung Kejagung lawan nepotisme habis-habisan!",
    "Nepotisme bikin semua usaha terasa sia-sia. Beresin sekarang!",
    "Kalau semua berdasarkan kemampuan, Indonesia pasti lebih maju!",
    "Kejagung, buktiin bahwa integritas itu lebih penting dari koneksi!",
    "Nepotisme bikin rakyat kecewa. Tapi Kejagung kasih harapan baru.",
    "Langkah kecil, tapi berdampak besar. Lawan nepotisme mulai dari sekarang!"

]

video_id = "@mildnews/video/435448346578574454"
base_id = 16923
kata_kunci = "kejaksaan agung"
tanggal_awal = datetime(2025, 1, 1)


for i, komentar in enumerate(komentar_list):
    random_date = tanggal_awal + timedelta(days=random.randint(0, 180))
    random_time = time(
        hour=random.randint(0, 23),
        minute=random.randint(0, 59),
        second=random.randint(0, 59)
    )
    random_datetime = datetime.combine(random_date, random_time)

    komentar_baru = KomentarMentah(
        id=base_id + i,
        video_id=video_id,
        kata_kunci=kata_kunci,
        username=generate_username(),
        comment=komentar,
        likes=random.randint(0, 500),
        replies=random.randint(0, 50),
        tanggal_komentar=random_datetime
    )
    session.add(komentar_baru)
    session.flush()

session.commit()
session.close()
print("✅ 100 komentar berhasil disimpan ke database.")
